services:

  webapi:
    image: coinpedia-web-api:latest
    container_name: coinpedia-web-api
    ports:
      - "8080:8080"
    depends_on:
      - seq
    networks:
      - backend

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "${SEQ_HOST_INGESTION_PORT}:5341"
      - "8081:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
