services:

  webapi:
    image: coinpedia-web-api:latest
    container_name: coinpedia-web-api
    ports:
      - "8080:8080"
    depends_on:
      seq:
        condition: service_started
      redis:
        condition: service_healthy

    networks:
      - backend

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "${SEQ_HOST_INGESTION_PORT}:5341"
      - "8081:80"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

networks:
  backend:
    driver: bridge
